### ISSUE TITLE
Nesting inside media queries

### ISSUE THREAD

**Issue by andylobban** [troch/postcss-responsive-values#2]
Example:
`@media (min-width: $tabletPortrait) {
    .contests__types {
        padding-left: responsive(whitespaceBase);
    }
}`
produces
`@media (min-width: 768px) {
    .contests__types {
        padding-left: 1.2rem;
    }
    @media (min-width: 980px) {
        .contests__types {
            padding-left: 2.4rem;
        }
    }
}`

**Comment by andylobban** [comment]
Those snippets didn't format well. Basically the plugin should create the second media query after the one it first appears inside. Currently it creates it nested inside the first.

**Comment by troch** [comment]
That would be what to expect, it's not designed to be used inside a media query since it creates some. Your example would still work though, cssnano should un-nest media queries.
